apiVersion: apps/v1
kind: Deployment
metadata:
  name: preveil-demo-deployment
  labels:
    app: preveil-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: preveil-demo
  template:
    metadata:
      labels:
        app: preveil-demo
    spec:
      containers:
      - name: preveil-demo
        image: flask-docker-demo-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001